module.exports = {
  interactive_games: {
    houre: 0,
    minute: 5,
    name_list: [
      "喵喵十消数字凑十比拼智商",
      "合成2048掉落碰撞畅快合成",
      "披萨餐厅策略餐厅经营",
      "麻将滑滑乐滑动消除麻将",
      "雀神来也",
      "货柜趣消除",
      "趣味叠叠乐",
      "排队上车",
      "方块拼图",
      "养猪猪",
      "京豆捕鱼",
      "消灭小萌星",
      "麻将凑十",
      "解压硬币",
      "2048方块",
      "无尽战歌",
    ],
    more_task_list: [
      { scroll: true },
      // round one
      { name: "百炼飞仙", dur_m: 16 },
      { name: "毛线大师", dur_m: 16 },
      { name: "点点2048", dur_m: 16 },
      { name: "麻将滑滑乐", dur_m: 16 },
      { name: "合成原始人", dur_m: 16 },
      { name: "无尽泡泡龙", dur_m: 16 },
      { name: "打螺丝王者", dur_m: 16 },
      { name: "数字喜加1", dur_m: 16 },
      { name: "合成2048", dur_m: 16 },
      { name: "战争之王", dur_m: 16 },
    ],
  },
};
