module.exports = {
  interactive_games: {
    houre: 0,
    minute: 5,
    name_list: [
      "雀神来也",
      "货柜趣消除",
      "趣味叠叠乐",
      "排队上车",
      "方块拼图",
      "养猪猪",
      "消灭小萌星",
      "麻将凑十",
      "解压硬币",
      "2048方块",
      "无尽战歌",
    ],
    more_task_list: [
      { scroll: true },
      // round one
      { name: "百炼飞仙", dur_m: 15 },
      { name: "毛线大师", dur_m: 15 },
      { name: "点点2048", dur_m: 15 },
      { name: "合成原始人", dur_m: 15 },
      { name: "无尽泡泡龙", dur_m: 15 },
      { name: "打螺丝王者", dur_m: 15 },
      { name: "数字喜加1", dur_m: 15 },
      { name: "战争之王", dur_m: 15 },
      // round two
      { name: "百炼飞仙", dur_m: 2 },
      { name: "毛线大师", dur_m: 2 },
      { name: "点点2048", dur_m: 1 },
      { name: "合成原始人", dur_m: 1 },
      { name: "无尽泡泡龙", dur_m: 1 },
      { name: "打螺丝王者", dur_m: 1 },
      { name: "数字喜加1", dur_m: 1 },
      { name: "战争之王", dur_m: 1 },
    ],
  },
};
